treehouses/cli

- modules/rename.sh
- package.json
Fixes error with inputting underscore/special characters when changing hostname
checks for
-special characters
-spaces
-length greater than 64
-no input
So that it conforms closely to debian hostname perferences shown below
> treehouses rename input check (fixes #315)

- README.md
- cli.sh
- modules/discover.sh
- modules/help.sh
- modules/speedtest.sh
- package.json
discover <rpi|ip|hostif|ping ip[ipaddress|url]
Usage: 
* `./cli.sh discover rpi` displays raspberry pis on network
* `./cli.sh discover ping 192.168.7.151` performs network scan of ip address
* `./cli.sh discover interface` displays host interface
* `./cli.sh discover scan 192.168.7.*` shows which devices are running
* `./cli.sh discover ports 192.168.7.151` shows which ports are open
> treehouses discover (fixes #448)

- modules/sshkey.sh
- package.json
use grep to find the github user's key, then use sed to delete them.
> refactor treehouses deletegithubusername (fixes #483)

- modules/sshkey.sh
- package.json
Fixes #497 
Added `(DEPRECATED)` to help sshkey under `deletegithubusername`
> update sshkey help (fixes #497)

- modules/temperature.sh
- package.json
Fixes #516
Added formula to convert from celsius to fahrenheit and updated help documentation. Users should now enter either "treehouses temperature fahrenheit" or "treehouses temperature celsius."
> treehouses temperature fahrenheit (fixes #516)

- modules/detectrpi.sh
- package.json
new hardware id used for my RPi4. I don't know why mine is different but we need to add it. Running treehouse image and got that hardware id.
> update detectrpi.sh (fixes #565)

- package.json
As per [SPDX](https://spdx.org/licenses/).
```AGPL-3.0-only``` Is valid.
```AGPL-3.0``` Is DEPRECATED.
> update package.json (fixes #573)

- modules/services.sh
- package.json
* Fixed `treehouses services [available|installed|running]` string output
* Reversed commands:
`treehouses services running string` ->` treehouses services running`
`treehouses services running` ->`treehouses services running full`
* Added `Available: `, `Installed: `, `Running: ` in front of each string output
* Moved tor port adding to the bottom of each `up` function (fixes #594)
> treehouses services fixes/updates (fixes #594)

- README.md
- _treehouses
- cli.sh
- modules/help.sh
- modules/remote.sh
- package.json
Fixes #590
Implements command `treehouses remote status` and `treehouses remote upgrade`
Combined several functions to reduce the possibility of things breaking on the remote app
`treehouses remote status` returns a single string in the form:
`<internet> <bluetooth mac> <image> <version> <detectrpi>`
`treehouses remote upgrade` returns true if an upgrade is available, false otherwise
`treehouses remote upgrade` might be removed?
Seems kind of useless
> treehouses remote [status|upgrade] added (fixes #590)

- modules/tor.sh
- package.json
Fixes #612
Added a check to see if there are any tor ports added.
You can test by running:
`./cli.sh tor destroy` warning: will remove all your tor ports
`./cli.sh tor start`
`./cli.sh tor status` will show an error message like below:
```
Error: there are no tor ports added.
'cli.sh add [localPort]' to add a port and be able to use the service
```
Adding any port (`./cli.sh tor add <port>`) will then allow normal usage.
> treehouses tor start port check (fixes #612)

- modules/services.sh
- package.json
Fixes #605
Fixes #606
* Added helper function for getting port numbers of specific services
`function get_port`
* Added functionality to get port numbers of individual services
`treehouses services planet port`
* Reworked functionality for getting port numbers of all services
`treehouses services ports`
* Added functionality to get urls (local or tor) for specific services
`treehouses services planet url local`
`treehouses services planet url tor`
> treehouses services ports & urls (fixes #605) (fixes #606)

- modules/services.sh
- package.json
Fixes #649
Changed from using `hostname` to using `treehouses networkmode` to get IP address when creating local url for services.
> treehouses services url with networkmode info (fixes #649)

- modules/services.sh
- package.json
Fixes #621
Adds a check_space function to check if there is enough free space on disk for the new service before pulling.
One problem is that you can only get the compressed image size which will obviously get larger when uncompressed.
An alternative would be to try to pull the image and when Docker throws an error catch that error instead of trying to check free space before pulling.
> treehouses services with check_space (fixes #621)

- modules/services.sh
- package.json
- templates/services/ntopng/ntopng_autorun
Fixes #618 
- https://github.com/ntop/ntopng
- The only problems i see with this is after a while the license expires (10mins? or 15mins?) 
- At that time the functionality regresses and it throws a plugin error
- Don't know what to do to fix that. Maybe delete the plugin. 
- There isn't really any docker images available to test for this except 1. 
- The rest are 4 years+ old and usually aren't for arm. 
`Important Information: Please Read
The licenses you can buy from this shop are valid only for binary packages that you can find at packages.ntop.org.
Licenses cannot be used with custom-built packages or on operating systems other than those listed at the packages site.
We will provide 5 days of installation support from the date of purchase, where you can ask us questions limited to: …
> treehouses services ntopng added (fixes #618)

- modules/services.sh
- package.json
Added error handling for creating yml files and running docker-compose up commands.
Created functions (`create_yml` and `docker_compose_up`) to facilitate error handling.
Considering adding error handling for the other docker-compose commands (`down`, `start`, `stop`)?
> treehouses services error handling

- modules/memory.sh
- package.json
Fixes #686
Since the main `memory()` function calls the other functions, we can't use local variables since local variables will be out of scope.
Reverting back to global variables fixes the issues.
> treehouses memory with global vars (fixes #686)

- README.md
- _treehouses
- cli.sh
- modules/detectrpi.sh
- modules/help.sh
- package.json
- Allows for us to query the model number directly
- Instead of "RPi4B+" we can get "c03112"
> treehouses detectrpi model (fixes #643)

- modules/networkmode.sh
- package.json
Fixes issue #709 treehouses networkmode info should only work when root
> treehouses networkmode info checkroot (fixes #709)

- _treehouses
- modules/help.sh
- modules/remote.sh
- package.json
Fixes #728
`./cli.sh remote version <version_number>` where `<version_number>` is the version of remote you want to check.
> treehouses remote minimum version check (fixes #728)

- modules/networkmode.sh
- Useless use of cat: https://en.wikipedia.org/wiki/Cat_(Unix)#Useless_use_of_cat
- https://stackoverflow.com/questions/7427262/how-to-read-a-file-into-a-variable-in-shell
Tested on RPi4
```
pi@raspberrypi:~/Documents/cli $ ./cli.sh networkmode
wifi
```
> treehouses networkmode remove cat

- modules/usb.sh
- package.json
- Useless use of cat: https://en.wikipedia.org/wiki/Cat_(Unix)#Useless_use_of_cat
- https://stackoverflow.com/questions/7427262/how-to-read-a-file-into-a-variable-in-shell
Tested on RPi4 Successfully:
```
pi@raspberrypi:~/Documents/cli $ sudo ./cli.sh usb off
The ethernet port on your Raspberry Pi 4 is connected. Turning off usb power will interfere with your ethernet connection. Do you wish to continue? Y or NN
```
> treehouses usb remove cat

- modules/services.sh
- package.json
Fixes #766
```
root@kjong:~/cli# ./cli.sh services pihole size
146M
root@kjong:~/cli# ./cli.sh services moodle size
148M
```
> treehouses services <service> size (fixes #766)

- _treehouses
- package.json
Fixes #847
```
root@treehouses:/home/pi/cli# cp ./_treehouses /etc/bash_completion.d/_treehouses
root@treehouses:/home/pi/cli# . /etc/bash_completion.d/_treehouses
```
> missing commands in _treehouses

- modules/services.sh
- package.json
Fixes #834
```
root@kjong:~/cli# ./cli.sh services couchdb url both
192.168.1.154:5984/_utils
masrx3fngdcup6cwihvplcgae5c6soppks425jplux24snv3nkfwtxad.onion:5984/_utils
```
Also fixed an issue with getting the tor url.
`if tor ; then` -> `if [ "$(tor status)" = "active" ]; then`
> treehouses services couchdb url (fixes #834)

- modules/services.sh
- package.json
Fixes #833
In favor of ```treehouses services <service_name> url``` to get both instead.
Or we can keep both and do "".
> treehouses services url (fixes #833)

- modules/help.sh
- package.json
```
root@raspberrypi:~/cli# ./cli.sh help
Usage: $BASENAME
help [command]                            gives you a more detailed info about the command or will output this
verbose <on|off>                          makes each command print more output (might not work with treehouses remote)
expandfs                                  expands the partition of the RPI image to the maximum of the SDcard
rename <hostname>                         changes hostname
password <password>                       changes the password for 'pi' user
sshkey <add|list|delete|deleteall|github> used for adding or removing ssh keys for authentication
version                                   returns the version of $BASENAME command
image                                     returns version of the system image …
```
> treehouses help as EOF (fixes #910)

- package.json
- tests/couchdb.bats
- tests/kolibri.bats
- tests/mariadb.bats
- tests/mastodon.bats
- tests/moodle.bats
- tests/netdata.bats
- tests/nextcloud.bats
- tests/ntopng.bats
- tests/pihole.bats
- tests/portainer.bats
- tests/privatebin.bats
- tests/seafile.bats
- tests/services.bats
```
root@raspberrypi:~/cli/tests# bats ./services.bats
✓  services planet info
✓  services planet install
✓  services planet up
✓  services planet restart
✓  services available
✓  services available full
✓  services running
✓  services running full
✓  services installed
✓  services installed full
✓  services ports
✓  services planet port
✓  services planet ps
✓  services planet url
✓  services planet autorun
✓  services planet autorun true
✓  services planet stop
✓  services planet down
✓  services planet cleanup
19 tests, 0 failures
root@raspberrypi:~/cli/tests#
```
> treehouses tests services url only (fixes #915)

- package.json
- tests/couchdb.bats
- tests/kolibri.bats
- tests/mariadb.bats
- tests/mastodon.bats
- tests/moodle.bats
- tests/netdata.bats
- tests/nextcloud.bats
- tests/ntopng.bats
- tests/pihole.bats
- tests/portainer.bats
- tests/privatebin.bats
- tests/seafile.bats
- tests/services.bats
```
root@raspberrypi:~/cli/tests# bats ./services.bats
✓  services planet info
✓  services planet install
✓  services planet up
✓  services planet restart
✓  services available
✓  services available full
✓  services running
✓  services running full
✓  services installed
✓  services installed full
✓  services ports
✓  services planet port
✓  services planet ps
✗  services planet url both
(from function `assert_output' in file /usr/lib/node_modules/bats-assert/src/assert.bash, line 247,
in test file services.bats, line 73)
`assert_output -p '80'' failed
-- output does not contain substring --
substring (1 lines):
80
output (2 lines):
ERROR: unknown command option
USAGE: cli.sh services url <local | tor>
--
✓  services planet autorun
✓  services planet autorun true
✓  services planet stop
✓ …
```
> treehouses tests services <service> icon (fixes #900)

- modules/detectbluetooth.sh
- package.json
> `treehouses detectbluetooth` refactor (fixes #952)(fixes #882)

- modules/networkmode.sh
- package.json
networkmode.sh has been modified to avoid error
> `treehouses networkmode` non-`info` message (fixes #931)

- modules/services.sh
- package.json
Fixes #1028
Before:
```
root@lilyxxx0w:~/cli# ./cli.sh services available
couchdb
kolibri
mariadb
mastodon
moodle
netdata
nextcloud
ntopng
pihole
planet
portainer
privatebin
seafile
```
After:
```
root@lilyxxx0w:~/cli# ./cli.sh services available
couchdb
mariadb
netdata
pihole
planet
portainer
privatebin
seafile
```
Also removed `check_arm` at line 88 since any incompatible services are being removed in `check_available_services` (which calls `services available` which calls `check_arm`)
> `treehouses services available` based on arm type (fixes #1028)

- cli.sh
- package.json
This fixes problems with eval because eval does 2 passes over its input. This is best solution I could find. Needs some testing Cheers.
tests:
```bash
root@treehouses:~/cli/tests# yes | ./test.sh all
Branch  - fixreports
Image   - release-126
Version - 1.17.19
1..466
ok 1  ap local test1 (check ap...press any key to continue)
ok 2  ap local test2 password (check ap...press any key to continue)
ok 3  ap internet test3 (check ap...press any key to continue)
ok 4  ap internet test4 password (check ap...press any key to continue)
ok 5  ap internet test5 password --ip=192.168.2.24 (check ap...press any key to continue)
not ok 6  apchannel
#
#
#
#
#
not ok 7  apchannel 6
#
#
#
#
#
ok 8  aphidden local test123 (check ap...press any key to continue)
ok 9  aphidden local test123 password (check …
```
> `treehouses` subcommands without `eval` (fixes #1032)

- README.md
- _treehouses
- modules/bluetooth.sh
- modules/help.sh
- package.json
Fixes #1048
`treehouses bluetooth` status output updated
> `treehouses bluetooth status` (fixes #1048)

- modules/bluetooth.sh
- package.json
Fixes #1080
updated `treehouses bluetooth` to have `checkargn $# 1`
> `treehouses bluetooth` checkargn (fixes #1080)

- README.md
- _treehouses
- modules/bluetooth.sh
- modules/help.sh
- package.json
```bash
root@treehouses:~/cli# ./cli.sh bluetooth log dfs
Error: Too many arguments.
Usage: cli.sh bluetooth <on|off|pause|mac|id|button|log>
Switches between hotspot / regular bluetooth mode, or displays the bluetooth mac address
Example:
cli.sh bluetooth
off
cli.sh bluetooth on
This will start the bluetooth server, which lets the user control the raspberry pi using the mobile app.
cli.sh bluetooth off
This will stop the bluetooth server, and bring everything back to regular mode.
This will also remove the bluetooth device id.
cli.sh bluetooth pause
Performs the same as 'cli.sh bluetooth off'
The only difference is that this command will not remove the bluetooth device id.
cli.sh bluetooth  mac
This will display the bluetooth MAC address
cli.sh bluetooth id
This will display the network …
```
> `treehouses bluetooth log` (fixes #1060)

- README.md
- _treehouses
- modules/bluetooth.sh
- modules/help.sh
- package.json
```bash
root@treehouses:~/cli# ./cli.sh bluetooth restart
Success: the bluetooth service has been restarted.
root@treehouses:~/cli# ./cli.sh bluetooth log
-- Logs begin at Mon 2020-04-20 21:11:36 UTC, end at Wed 2020-04-22 23:49:37 UTC. --
Apr 20 21:11:40 treehouses systemd[1]: Started Bluetooth server.
Apr 20 21:11:41 treehouses python3[371]: Debug logs enabled
Apr 20 21:11:41 treehouses systemd[1]: Condition check resulted in Bluetooth service being skipped.
Apr 20 21:11:47 treehouses systemd[1]: Starting Bluetooth service...
Apr 20 21:11:47 treehouses bluetoothd[571]: Bluetooth daemon 5.50
Apr 20 21:11:47 treehouses systemd[1]: Started Bluetooth service.
Apr 20 21:11:47 treehouses bluetoothd[571]: Starting SDP server
Apr 20 21:11:47 treehouses bluetoothd[571]: Bluetooth management …
```
> `treehouses bluetooth restart` (fixes #1093)

- _treehouses
- modules/bluetooth.sh
- package.json
```bash
root@treehouses:~/cli# ./cli.sh bluetooth log sdfs
Argument not valid; leave blank or use "follow"
root@treehouses:~/cli# ./cli.sh bluetooth log follow sdfs
Error: Too many arguments.
Usage: cli.sh bluetooth [on|off|pause|restart|mac|id|button|status|log]
Switches between hotspot / regular bluetooth mode, or displays the bluetooth mac address
Example:
cli.sh bluetooth
on
cli.sh bluetooth status
bluetooth service status: on
rpibluetooth service status: on
cli.sh bluetooth on
This will start the bluetooth server, which lets the user control the raspberry pi using the mobile app.
cli.sh bluetooth off
This will stop the bluetooth server, and bring everything back to regular mode.
This will also remove the bluetooth device id.
cli.sh bluetooth pause
Performs the same as 'cli.sh …
```
> `treehouses bluetooth log follow` (fixes #1120)

- README.md
- _treehouses
- modules/help.sh
- modules/upgrade.sh
- package.json
- tests/upgrade.bats
```bash
root@treehouses:~/cli# ./cli.sh upgrade bluetooth
Successfully updated and restarted bluetooth server
root@treehouses:~/cli# rm -rf /usr/local/bin/bluetooth-server.py
root@treehouses:~/cli# ./cli.sh upgrade bluetooth         Successfully updated and restarted bluetooth server
root@treehouses:~/cli# ls /usr/local/bin
bluetooth-server.py  hub-ctrl     sl         youtube-dl
do_autorun           jsonschema   terraform
docker-compose       __pycache__  wsdump.py
root@treehouses:~/cli# ./cli.sh upgrade bluetooth dfsd
Error: Too many arguments.
Usage: cli.sh upgrade [tag|bluetooth] [--check]
Upgrades cli.sh package using npm
Example:
cli.sh upgrade
This will upgrade the cli.sh package using npm and will try to install the latest version of cli.sh running on your system
If the latest …
```
> `treehouses upgrade bluetooth`

- modules/upgrade.sh
- package.json
```bash
root@treehouses:~/cli# ./cli.sh upgrade bluetooth
Successfully updated and restarted bluetooth server
root@treehouses:~/cli# ./cli.sh upgrade bluetooth sdfdaf
Error: branch specified not found on bluetooth server repository
root@treehouses:~/cli# ./cli.sh upgrade bluetooth multioverhaul
Successfully updated and restarted bluetooth server
root@treehouses:~/cli# cat /usr/local/bin/bluetooth-server.py
#!/usr/bin/python3
import logging
import logging.handlers
import os
import signal
import subprocess
import sys
import threading
import socket
import string
import random
import bluetooth
import dbus
def _ExceptionHandler(exc_type, exc_value, exc_traceback):
sys.__excepthook__(exc_type, exc_value, exc_traceback)
os.kill(os.getpid(), signal.SIGINT)
#This is what gets spawned by the server …
```
> `treehouses upgrade bluetooth <branch>` (fixes #1127)

- .gitattributes
- package.json
Doesn't seem to fix the problem. I think the problem lies with the other repository. 
```bash
Gaming@DESKTOP-RIQ2OSF MINGW64 ~/Desktop/cli (gitattrib)
$ vagrant up
Bringing machine 'cli' up with 'virtualbox' provider...
==> cli: Importing base box 'treehouses/buster64'...
==> cli: Matching MAC address for NAT networking...
==> cli: Checking if box 'treehouses/buster64' version '0.12.5' is up to date...
==> cli: Setting the name of the VM: cli
==> cli: Clearing any previously set network interfaces...
==> cli: Preparing network interfaces based on configuration...
cli: Adapter 1: nat
==> cli: Forwarding ports...
cli: 22 (guest) => 2222 (host) (adapter 1)
==> cli: Running 'pre-boot' VM customizations...
==> cli: Booting VM...
==> cli: Waiting for machine to boot. This may take a few …
```
> add `.gitattributes` to force unix line endings (fixes #1126)

- modules/tor.sh
- package.json
```bash
root@treehouses:~/cli# ./cli.sh tor notice nowq
Error: only 'on', 'off', 'now', 'add', 'delete', and 'list' options are supported.
```
> `treehouses tor notice` error message (fixes #936)

- modules/detectrpi.sh
- package.json
```bash
root@treehouses:~/cli# ./cli.sh detectrpi full
Raspberry Pi 4 Model B Rev 1.2
root@treehouses:~/cli# ./cli.sh detectrpi fullq
Error: only 'detectrpi', 'detectrpi model', and 'detectrpi full' commands supported
root@treehouses:~/cli# ./cli.sh help detectrpi
Usage: cli.sh detectrpi
Detects the hardware version
Example:
cli.sh detectrpi
Prints the Raspberry Pi name
cli.sh detectrpi model
Prints the model number of the RPi
cli.sh detectrpi full
Prints the full model of the RPi
root@treehouses:~/cli#
```
> `treehouses detectrpi full` error message (fixes #951)

- README.md
- _treehouses
- modules/help.sh
- modules/led.sh
- modules/power.sh
- package.json
Fixes #1052 
`treehouses power <scaling_governor_setting>`
There are 5 scaling governor settings that the RPi can switch to:
1. `ondemand`: **default**, moves speed from min to max and back at a % of load
1. `conservative` : gradually switch frequencies at % of load
1. `userspace` : use user specified frequencies
1. `powersave`: all cores set at minimum frequency
1. `performance` : all cores set at maximum frequency
`treehouses power freq` can be used to check the CPU frequency.
> `treehouses power` (fixes #1052)

- modules/power.sh
- package.json
Fixes #1180 
Help menu appears now when the user incorrectly uses `treehouses power`
> `treehouses power` help on error (fixes #1180)

- _treehouses
- package.json
Fixes #1182 
The `treehouses usb` command wasn't working as the command wasn't added to `_treehouses`.
> `treehouses usb` tab completion (fixes #1182)

- modules/usb.sh
- package.json
Fixes #1183 
Help menu appears now when the user incorrectly uses `treehouses usb on/off`
> `treehouses usb` help on error (fixes #1183)

- README.md
- _treehouses
- modules/help.sh
- modules/password.sh
- package.json
Fixes #540 
A simpler alternative to PR #1171 that modifies the `/etc/passwd` file by adding a `!` to the `pi` user
> `treehouses password disable` & `enable` (fixes #540)

- modules/bluetooth.sh
- package.json
Fix spacing in the bluetooth_help function
> `treehouses help bluetooth` spacing (fixes #1195)

- modules/services.sh
- package.json
```bash
root@treehouses:~/cli# ./cli.sh services nextcloud install
Pulling nextcloud ... done
nextcloud installed
modify default environment variables by running 'cli.sh services nextcloud environment edit'
root@treehouses:~/cli# ./cli.sh services mongodb install
ERROR: The Compose file '/srv/mongodb/mongodb.yml' is invalid because:
services.mongodb.environment contains an invalid type, it should be an object, or an array
retrying pull in 6 seconds
ERROR: The Compose file '/srv/mongodb/mongodb.yml' is invalid because:
services.mongodb.environment contains an invalid type, it should be an object, or an array
retrying pull in 6 seconds
ERROR: The Compose file '/srv/mongodb/mongodb.yml' is invalid because:
services.mongodb.environment contains an invalid type, it should be an object, or an …
```
> `treehouses services <service> install` sleepy try (fixes #946)

- Vagrantfile
- package.json
please run `vagrant up`
then `vagrant ssh`
and last `treehouses ...`
> update Vagrantfile (fixes #1246)

- modules/globals.sh
- package.json
When hitting `ctrl+z` when running `treehouses heavymetal` it isn't trapped by the spinner. So the spinner will keep running even though the cli has been sent to the background. This fixes that. Trying ctrl+z before and after this PR shows the change.
> `treehouses` stop spinner with ctrl+z (fixes #1289)

- package.json
- services/install-mongodb.sh
Add port 28017 for the default MongoDB web interface
> `treehouses services mongodb` port 28017 (fixes #1314)

- package.json
- services/install-couchdb.sh
```bash
root@treehouses:~/cli# ./cli.sh services couchdb install
Pulling couchdb ... done
couchdb installed
root@treehouses:~/cli# ./cli.sh services couchdb up
Creating network "couchdb_default" with the default driver
Creating couchdb_couchdb_1 ... done
couchdb built and started
root@treehouses:~/cli# ./cli.sh services couchdb port
5984
root@treehouses:~/cli# ./cli.sh services couchdb url
192.168.0.23:5984/_utils
root@treehouses:~/cli# cd tests
root@treehouses:~/cli/tests# cd services/
root@treehouses:~/cli/tests/services# bats ./couchdb.bats
✓  services couchdb info
✓  services couchdb install
✓  services couchdb up
✓  services couchdb restart
✓  services available
✓  services running
✓  services running full
✓  services installed
✓  services installed full
✓  services ports
✓  services …
```
> `treehouses couchdb` more EOF (fixes #1293)

- modules/changelog.sh
- package.json
update `treehouses changelog compare` to work with new `CHANGELOG.md` format
fixes #1304
> `treehouses changelog` new format (fixes #1304)

- package.json
add -f to ln in postinstall
fixes #1323
- last major vagrant issue
- vagrant can now build images without problems
> update `package.json` (fixes #1323)

- package.json
- services/install-invoiceninja.sh
Fixes #1339 
```
Pulling db   ... done
Pulling app  ... done
Pulling web  ... done
Pulling cron ... done
invoiceninja installed
modify default environment variables by running 'cli.sh services invoiceninja config edit'
root@treehouses:~/cli# ./cli.sh services invoiceninja up
valid yml
Creating network "invoiceninja_default" with the default driver
Creating volume "invoiceninja_db" with default driver
Creating volume "invoiceninja_storage" with default driver
Creating volume "invoiceninja_logo" with default driver
Creating volume "invoiceninja_public" with default driver
Creating invoiceninja_cron_1 ... done
Creating invoiceninja_db_1   ... done
Creating invoiceninja_app_1  ... done
Creating invoiceninja_web_1  ... done
invoiceninja built and started
root@treehouses:~/cli# ./cli.sh …
```
> `treehouses services invoiceninja port` 8090 (fixes #1339)

- README.md
- _treehouses
- modules/camera.sh
- modules/help.sh
- package.json
allows the user to detect if there is a camera plugged in, and what version of the camera it is.
- needs testing for HQ camera and camera v2
- IR camera is v2
- nothing added to test.bats
fixes #1315
> `treehouses camera detect` (fixes #1315)

- modules/camera.sh
- package.json
no longer needs reboot to enable and disable the camera
- fixes #1300
> `treehouses camera on` & `off` refactor (fixes #1300)

- README.md
- modules/help.sh
- modules/services.sh
- package.json
- services/install-bookstack.sh
- tests/services/bookstack.bats
fixes #1340 
```
root@treehouses:/home/pi/cli# ./cli.sh services bookstack install
Pulling bookstack_db ... done
Pulling bookstack    ... done
bookstack installed
modify default environment variables by running 'cli.sh services bookstack config edit'
root@treehouses:/home/pi/cli# ./cli.sh services bookstack up
valid yml
Creating network "bookstack_default" with the default driver
Creating bookstack_db ... done
Creating bookstack    ... done
bookstack built and started
root@treehouses:/home/pi/cli# ./cli.sh services bookstack start
Starting bookstack_db ... done
Starting bookstack    ... done
bookstack started
root@treehouses:/home/pi/cli# ./cli.sh services bookstack ps
1a66794a1d34        linuxserver/bookstack             "/init"                  31 seconds ago      Up 27 seconds …
```
> `treehouse services bookstack` (fixes #1340)

- modules/gpio.sh
- package.json
fixes #1387
- added `checkrpi`
> `treehouses gpio` only rpi (fixes #1387)

- modules/sshtunnel.sh
- package.json
Fixes #1471
* Filters by external ports instead of local ports when removing ports
* Fixes partial matching issues
> `treehouses sshtunnel remove port` external (fixes #1471)

- modules/usb.sh
- package.json
> `treehouses usb` refactor (fixes #1580) 

- modules/memory.sh
- package.json
> `treehouses memory` no dash outputs (fixes #1671)

- package.json
- services/install-pylon.sh
Fixes #1682
Testing part 1 is mainly making sure nothing is broken.
Testing part 2 is making sure `treehouses services config edit request` and `treehouses services config edit send` now work for pylon. 
1. Run `./cli.sh services pylon cleanup` if pylon is already installed.
2. Run `./cli.sh services pylon install`.
3. Run `./cli.sh services pylon up`.
4. Run `./cli.sh services pylon url` and use the first url in browser to run pylon.
5. Check to see if app still asks for username and password and then enter \<username> for username and \<password> for password.
6. You should now be able to use the app.
1. To make sure I fixed the issue, run `./cli.sh services pylon down` if it is still running.
2. Run `./cli.sh services pylon config edit request` and copy the output.
3. Paste that …
> `treehouses services pylon` with env (fixes #1682)

- modules/bluetooth.sh
- modules/upgrade.sh
- package.json
improves the bluetooth upgrade function to work when sent from remote. requires an up to date treehouses image, or make sure your rpibluetooth service is the same as master https://github.com/treehouses/builder/blob/master/install/etc/systemd/system/rpibluetooth.service
- fixes #1607
> `treehouses upgrade bluetooth` targeted kill (fixes #1607)

- modules/clone.sh
- package.json
show progress when running `treehouses clone` using inbuilt `dd status`
more detailed progress bar can be made by intercepting `dd` pipe with `pv`
https://askubuntu.com/questions/215505/how-do-you-monitor-the-progress-of-dd
- fixes #1705
> `treehouses clone` progress (fixes #1705)

- modules/sshkey.sh
- package.json
fixes #1712 
ability to delete keys without inputting quotes
```
treehouses sshkey delete ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINPobRqfqhCx7x0ydvuOq3gUfkOTIF7O4wiBBSk0uzg9 root@treehouses
Key deleted from root keys.
Key not found in pi keys.
```
> `treehouses sshkey delete` refactor (fixes #1712)

- README.md
- _treehouses
- modules/help.sh
- modules/ssh.sh
- package.json
fixes #1646
---
Enable 2fa for ssh:
```
$ treehouses ssh 2fa enable
```
then set up pi user for 2fa:
```
$ treehouses ssh 2fa add pi
```
follow it step by step, scan the qr code on your phone
Next time try ssh **without** a ssh key, you'll be prompted with:
```
Password: 
Verification code: 
```
You can use `ssh -i ./ pi@....` to use an invalid file as key, this has the same effect of not using a key at all.
> `treehouses ssh 2fa` (fixes #1646)

- README.md
- _treehouses
- modules/help.sh
- modules/message.sh
fixes #1700
How to test:
From the cli directory, checkout the branch message-gitter-receivefrom-mark-read. To set up an apikey for gitter, follow these instructions:
```
git checkout message-gitter-receivefrom-mark-read
./cli.sh message gitter apikey
```
follow the instructions that show up
then:
choose a Gitter channel where you have unread messages, it could also be with a user.
`./cli.sh message gitter receivefrom mark-read <channel/user>`
You should have unread messages displayed and you can check if they are read by running the above command again, where you should see nothing but: 
`You have no unread messages at the moment`
> ` treehouses message gitter send|receive` (fixes #1700)

- README.md
- _treehouses
- modules/help.sh
- modules/message.sh
- package.json
fixes https://github.com/treehouses/cli/issues/2014
> `treehouses message slack channels`(fixes #2014)

- README.md
- _treehouses
- modules/help.sh
- modules/message.sh
- package.json
fixes https://github.com/treehouses/cli/issues/2004
> `treehouses message slack read`(fixes #2004)

- README.md
- _treehouses
- modules/help.sh
- modules/message.sh
- package.json
fixing https://github.com/treehouses/cli/issues/2005
> `treehouses message slack show|mark` (fixes #2005)

- modules/message.sh
- package.json
fixes https://github.com/treehouses/cli/issues/2019
> 'treehouses message slack <action> <channelname>' (fixes #2019)

- modules/led.sh
- package.json
Fixes `treehouses led random` not having all the led subcommands
> `treehouses led random` 3 lines (fixes #2046)

- README.md
- modules/help.sh
- package.json
Fixed the `message` command to its correct format.
> `treehouses message` formatting (fixes #2050)

- package.json
- tests/changelog.bats
Updating `changelog.bats` so it doesn't accidentally remove the changelog from `usr/lib...`
> update `tests/changelog.bats` (fixes #2095)

- _treehouses
- modules/sshtunnel.sh
- package.json
Added the option `name`:
Example: treehouses sshtunnel key name [SSH key name]
Only `name` without any values will list the current SSH key name.
Adding a value after will name the SSH key to the value.
> `treehouses sshtunnel key name` (fixes #2273)

- modules/services.sh
- package.json
> `treehouses services` also ready for `docker compose` (fixes #2294)

- modules/vnc.sh
- package.json
> `treehouses vnc` smoother help (fixes #1909) (fixes #2136)
