treehouses/cli

- cli.sh
- package.json
here's what I tried:
treehouses wifi Network Password
treehouses staticwifi
then you should be able to see the new ip using
ip addr
> Fix treehouses staticwifi

- cli.sh
> treehouses version show both installed and latest version (fixes #98)

- modules/upgrade.sh
- package.json
Signed-off-by: Ignacio Rodríguez <ignacio@sugarlabs.org>
> Improve treehouses upgrade

- package.json
- templates/gpio-button.py
> Reduce CPU utilization of treehouses button

- README.md
- cli.sh
- modules/ap.sh
- modules/bridge.sh
- modules/globals.sh
- package.json
- templates/network/dnsmasq/bridge
- templates/network/dnsmasq/hotspot
- templates/network/wlan0/bridge
- templates/network/wlan0/hotspot
- templates/network/wlan0/hotspot_shared
> Add custom base IP for AP

- cli.sh
- modules/tor.sh
- package.json
- templates/network/tor_report.sh
I also changed it to fully use root -- since there were some problems such as pi user not being able to read /var/lib/tor/treehouses
> treehouses tor - now reports the address/ports to gitter

- modules/globals.sh
- modules/networkmode.sh
- package.json
Verify if the iface exists on get_ipv4_ip
> Show the eth0/wlan0 ip if present when network modeis default (fixes #288)

- modules/default.sh
- package.json
Updating default.sh (Fixes #310 #311 #312 #313)
> update treehouses default (fixes #310) (fixes #311) (fixes #312) (fixes #313)

- modules/locale.sh
- package.json
> typo in help

- modules/openvpn.sh
- package.json
I corrected the typo for open vpn
> treehouses openvpn typo (fixes #318)

- README.md
- package.json
Fixes #339 add badges README.md
> Fixes #339 add badges README.md

- modules/tor.sh
- package.json
> new syntax for treehouses tor add (fixes #366) (fixes #368)

- package.json
> update package.json (fixes 378)

- modules/sshtunnel.sh
> Revert "treehouses sshtunnel notice now with check (fixes #380)"

- README.md
- package.json
> npm-analyzer: max branding (fixes #403)

- README.md
- cli.sh
- modules/help.sh
- modules/temperature.sh
- package.json
creates new command that displays rpi core cpu temperature with 1 subcommand
> treehouses temperature (fixes #392)

- README.md
- cli.sh
- modules/help.sh
- modules/speedtest.sh
- package.json
add new feature to test internet download and upload speed
fixs #433
> treehouses speedtest (fixes #433)

- _treehouses
- modules/led.sh
- package.json
Add a new `led thanksgiving` lighting mode
> treehouses led thanksgiving (fixes #513)

- modules/led.sh
> treehouses led help typo

- README.md
- _treehouses
- cli.sh
- modules/help.sh
- modules/reboot.sh
- modules/reboots.sh
- package.json
```
Usage: cli.sh reboots <now|in|cron|daily|weekly|monthly>
Reboots system at selected time
Example:
cli.sh reboots daily
System will reboot daily at 00:00
cli.sh reboots in 120
System will reboot in 120 seconds. ctrl+c to cancel.
cli.sh reboots cron "0 * * * *"
Rebooting with frequency of "0 * * * *" added
Set frequency: * * * * *
│ │ │ │ │
│ │ │ │ └── day of the week    (* | #/# | 0 - 6 or Sun to Sat)
│ │ │ └──── month              (* | #/# | 1 - 12)
│ │ └────── day of the month   (* | #/# | 1 - 31)
│ └──────── hour               (* | #/# | 0 - 23)
└────────── minute             (* | #/# | 0 - 59)
```
> treehouses reboots (fixes #443)

- modules/globals.sh
- package.json
> globals: new check missing packages (fixes #576)

- modules/ap.sh
- modules/bridge.sh
- package.json
- remove a-z regex
- need more work
> treehouses ap/bridge no regex (fixes #579)

- modules/services.sh
- package.json
Fixes #583 
```
treehouses services available string
treehouses services installed string
treehouses services running string
```
```
root@kjong:~/cli# ./cli.sh services available
kolibri [kolibri_autorun\|kolibri_yml.sh]
moodle [moodle_autorun\|moodle_yml.sh]
nextcloud [nextcloud_autorun]
pihole [pihole_autorun\|pihole_yml.sh]
planet [planet_autorun\|planet_yml.sh]
privatebin [privatebin_autorun\|privatebin_yml.sh]
root@kjong:~/cli# ./cli.sh services available string
kolibri moodle nextcloud pihole planet privatebin
```
```
root@kjong:~/cli# ./cli.sh services installed
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                      PORTS                                        NAMES
1d460546f989 …
```
> treehouses services string output added (fixes #583)

- _treehouses
- modules/led.sh
- package.json
please test the led.sh
I have added the Carneval LED blink , please test.
Function called 'carneval'
> treehouses led carneval (fixes #593)

- README.md
- _treehouses
- cli.sh
- modules/ap.sh
- modules/bootoption.sh
- modules/coralenv.sh
- modules/default.sh
- modules/ethernet.sh
- modules/expandfs.sh
- modules/feedback.sh
- modules/globals.sh
- modules/help.sh
- modules/led.sh
- modules/locale.sh
- modules/ntp.sh
- modules/openvpn.sh
- modules/rtc.sh
- modules/sshtunnel.sh
- modules/staticwifi.sh
- modules/timezone.sh
- modules/verbose.sh
- modules/wifi.sh
- modules/wificountry.sh
- modules/wifihidden.sh
- package.json
This creates a config file called .treehouses in the script folder. 
We can use this for future variables to save between sessions.
$LOGFILE is saved between sessions by using this $CONFIGFILE . 
/dev/null is the void so no output comes from commands. 
Setting /dev/null to "" instead prints all commands stdoutput and stderror to screen for commands like `treehouses bluetooth on` and etc.
> treehouses verbose added (fixes #169)

- modules/services.sh
- package.json
Fixes #596
Added checks to see if tor is active and whether tor port is already present
> treehouses services tor check (fixes #596)

- README.md
- _treehouses
- cli.sh
- modules/help.sh
- modules/remote.sh
- modules/services.sh
- package.json
`treehouses services available` ->
```
kolibri moodle nextcloud pihole planet privatebin
```
`treehouses services available full` ->
```
kolibri [kolibri_autorun|kolibri_yml.sh]
moodle [moodle_autorun|moodle_yml.sh]
nextcloud [nextcloud_autorun]
pihole [pihole_autorun|pihole_yml.sh]
planet [planet_autorun|planet_yml.sh]
privatebin [privatebin_autorun|privatebin_yml.sh]
```
`treehouses remote services available` ->
```
Available: kolibri moodle nextcloud pihole planet privatebin
```
> treehouses services string

- _treehouses
- modules/led.sh
- package.json
Issue #591 - treehouses led valentine?
Updated led.sh
> treehouses led valentine (fixes #591)

- modules/services.sh
- package.json
Fixes #616
```
root@kjong:~/cli# ./cli.sh services planet info
https://github.com/open-learning-exchange/planet
"Planet Learning is a generic learning system built in Angular
& CouchDB."
```
```
root@kjong:~/cli# ./cli.sh services privatebin info
https://github.com/treehouses/privatebin
"A minimalist, open source online pastebin where the server has
zero knowledge of pasted data. Data is encrypted/decrypted in the
browser using 256 bits AES. https://privatebin.info/"
```
Any suggestions on what to add besides github link and a short description?
> treehouses services <service> info (fixes #616)

- modules/services.sh
- package.json
Fixes #625
`treehouses services <service> restart`
> treehouses services <service> restart (fixes #625)

- README.md
- package.json
- Add install section
- Add features section
- Add about section
- Add short description in about me
- Add install instructions
*Testing*:
*Open* https://github.com/treehouses/cli/tree/update-readme
*And scroll down to see the new Readme.md*
> update README.md (fixes #640)

- modules/wificountry.sh
- package.json
Modified wificountry so that it displays the current wificountry setting if no argument is given.
> treehouses wificountry (fixes #676)

- modules/services.sh
- package.json
- templates/services/netdata/netdata_autorun
- templates/services/netdata/netdata_yml.sh
under /template/service, add netdata subdir
add netdata_autorun and netdata_yml.sh
> treehouses services netdata (fixes #671)

- modules/led.sh
- package.json
Fixed issue #700. Added new festival to the file led.sh
> treehouses led onam (fixes #700)

- modules/memory.sh
- modules/temperature.sh
- package.json
Fixes issue #554 check of bc pkg for treehouses temperature and memory
> check for bc pkg in temperature & memory (fixes #554)

- modules/led.sh
- package.json
> treehouses led carnival spelling (fixes #717)

- modules/services.sh
- package.json
> treehouses services add tor port using screen (fixes #698)

- modules/detectrpi.sh
- package.json
Modified detectrpi.sh to display full RPI information
> treehouses detectrpi full (fixes 722)

- modules/password.sh
- package.json
- Pipe spawns its own sub process. We can remove pipe and echo in one fell swoop
- https://brbsix.github.io/2015/11/29/bash-scripting-dos-and-donts/
Tested on RPi4 Successfully:
```
pi@raspberrypi:~/Documents/cli $ sudo ./cli.sh password leroy
Success: the password has been changed
```
> treehouses password remove echo

- modules/remote.sh
- package.json
Fixes#734 treehouses remote version no number check
> treehouses no number check (fixes #734)

- README.md
- _treehouses
- cli.sh
- modules/help.sh
- modules/sdbench.sh
- modules/usb.sh
- package.json
Added sdbench.sh to write and read the SDcard speed
> treehouses sdbench (fixes #730)

- modules/clone.sh
- package.json
Fixes #769 clone help is burning.
> treehouses help clone (fixes #769)

- modules/password.sh
- package.json
password.sh file modified to solve the password no input error
> treehouses password not empty (fixes #754)

- cli.sh
- modules/blocker.sh
- modules/bridge.sh
- modules/coralenv.sh
- modules/default.sh
- modules/discover.sh
- modules/led.sh
- modules/log.sh
- modules/memory.sh
- modules/networkmode.sh
- modules/rename.sh
- modules/restore.sh
- modules/services.sh
- modules/sshkey.sh
- modules/sshtunnel.sh
- modules/temperature.sh
- modules/upgrade.sh
- modules/vnc.sh
- modules/wificountry.sh
- package.json
- services/install-kolibri.sh
- services/install-mastodon.sh
- services/install-ntopng.sh
- services/install-pihole.sh
Fixes #752 cleanse trailing whitespace everywhere
> remove all trailing whitespaces (fixes #752)

- package.json
Fixes #772 add missing keywords to package.json
> missing keywords in package.json (fixes #772)

- modules/services.sh
- package.json
> treehouses services <service> up before install (fixes #817)

- README.md
- _treehouses
- modules/help.sh
- modules/services.sh
- package.json
Added CouchDB to _treehouses, Package.json
> treehouses services couchdb missing stuff (fixes #835)

- modules/led.sh
- package.json
> treehouses help led newyear (fixes #848)

- modules/ntp.sh
- package.json
Fixes #798 treehouses ntp wrong exit code
> treehouses ntp exit code 1 (fixes #798)

- modules/rtc.sh
- package.json
Fixes #799 treehouses rtc wrong exit codes
> treehouses rtc wrong exit codes (fixes #799)

- modules/camera.sh
- package.json
Fixes #797 treehouses camera exit not needed
> treehouses camera no exit 0 (fixes #797)

- modules/ap.sh
- package.json
Fixes #795 treehouses ap wrong exit code
> treehouses ap exit code 1 (fixes #795)

- modules/aphidden.sh
- package.json
Fixes #796 treehouses aphidden wrong exit code
> treehouses ap hidden exit code 1 (fixes #796)

- README.md
- _treehouses
- modules/help.sh
- modules/services.sh
- package.json
- services/install-mariadb.sh
```
pi@treehouses:~/git_repo/cli $ sudo ./cli.sh services mariadb install
Pulling mariadb ... done
mariadb installed
pi@treehouses:~/git_repo/cli $ sudo ./cli.sh services mariadb up
mariadb_mariadb_1 is up-to-date
mariadb built and started
pi@treehouses:~/git_repo/cli $ sudo ./cli.sh services mariadb port
3306
pi@treehouses:~/git_repo/cli $ sudo ./cli.sh services mariadb size
275M
pi@treehouses:~/git_repo/cli $ sudo ./cli.sh services mariadb stop
Stopping mariadb_mariadb_1 ... done
mariadb stopped
```
......
please review.
> treehouses services mariadb

- modules/services.sh
- package.json
> treehouses services check_space on install (fixes #859)

- modules/staticwifi.sh
- package.json
> treehouses staticwifi min arguments check (fixes #710)

- modules/remote.sh
- package.json
> treehouses remote 7 args check (fixes #891)

- package.json
- tests/sshkey.bats
```
root@raspberrypi:~/cli# cd tests
root@raspberrypi:~/cli/tests# bats ./sshkey.bats
✓  sshkey add "test"
✓  sshkey list
✓  sshkey delete "test"
✓  sshkey deleteall (manually test w/out bats - deletes all sshkeys)
✓  sshkey github adduser dogi
✓  sshkey github deleteuser dogi
✓  sshkey github addteam (manually test w/out bats - needs access token)
7 tests, 0 failures
root@raspberrypi:~/cli/tests# cd ..
root@raspberrypi:~/cli# ./cli.sh sshkey list
==== root keys ====
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDZHlwTVJJ3zdx7yGAQUYzJfKx6jEjqlLTzwc9hDoADWg5bThHjUFTyGkWeEFSEvWNq1rnd6gEqZBiuDAkg2hAs0gbLDTKHxjRY8q8vMNNiIYN4QBJkeb0emh6G2dJ+KSTnp6/OpAwKs4M84WMOqtmhRhr28KJP+21VrnMLGR8HLQOJXj2FHtUrj6CXqpcRws8p4ro+9gMD6mh97wdH5KcAus3rdcU5At+E7VuEBhYXSXeH9DiCFWVnDe0lEyDeVqQGHiS2yl79dodEAGgczxNk+hKFtTMhoRpn …
```
> treehouses tests no sshkey deleteall (fixes #912)

- _treehouses
- modules/services.sh
- package.json
> treehouses services available exclude README.md (fixes #917)

- modules/services.sh
- package.json
> treehouses services <service> port refactor (fixes #920)

- modules/tor.sh
- package.json
Fixes #934 
Fixes #935
```
root@treehouses:~/test1/cli# ./cli.sh feedback "dfsfsd"
Thanks for the feedback!
root@treehouses:~/test1/cli# ./cli.sh tor notice now
Thanks for the feedback!
root@treehouses:~/test1/cli#
```
> `treehouses tor notice now` internal feedback (fixes #934)

- README.md
- _treehouses
- modules/detectarm.sh
- modules/help.sh
- package.json
- tests/detectarm.bats
Implements part of #943
```
root@kjong:~/cli# ./cli.sh detectarm
v7l
```
> `treehouses detectarm`

- README.md
https://github.com/treehouses/cli/tree/dev-help
https://github.com/treehouses/cli/blob/dev-help/README.md#L116-L126
> update `README.md` (fixes #960)

- cli.sh
- modules/config.sh
- modules/feedback.sh
- modules/rtc.sh
- package.json
```bash
root@treehouses:~/test1/cli/tests# yes | ./test.sh all
Branch  - movevars
Image   - release-126
Version - 1.17.11
1..466
ok 1  ap local test1 (check ap...press any key to continue)
ok 2  ap local test2 password (check ap...press any key to continue)
ok 3  ap internet test3 (check ap...press any key to continue)
ok 4  ap internet test4 password (check ap...press any key to continue)
ok 5  ap internet test5 password --ip=192.168.2.24 (check ap...press any key to continue)
ok 6  apchannel
ok 7  apchannel 6
ok 8  aphidden local test123 (check ap...press any key to continue)
ok 9  aphidden local test123 password (check ap...press any key to continue)
ok 10  aphidden internet test321 (check ap...press any key to continue)
ok 11  aphidden internet test321 password (check ap...press any …
```
> herd variables in cli.sh (fixes #984)

- package.json
- services/install-seafile.sh
> `treehouses services seafile info` improvement (fixes #1022)

- README.md
- _treehouses
- modules/help.sh
- modules/remote.sh
- package.json
Fixes #1013
@sriharivishnu
I'm not sure how you process it on your end. Let me know if there any changes that need to be made regarding escapes or quotations and such.
> `treehouses remote json` (fixes #1013)

- README.md
- _treehouses
- modules/help.sh
- modules/inspire.sh
- package.json
Fixes #1009
added `treehouses inspire` module with:
- joke
- quote of the day
- random
> `treehouses inspire` (fixes #1009)

- _treehouses
- modules/led.sh
- package.json
- tests/led.bats
Fixes issue #964
Added new holiday to list of `treehouses led` command
> `treehouses led heavymetal` (fixes #964)

- _treehouses
- package.json
Add treehouses tor notice to (fixes#1040)
> add `treehouses tor notice` to `_treehouses` (fixes #1040)

- modules/networkmode.sh
- package.json
networkmode.sh has been modified
> `treehouses networkmode` non-`info` message (fixes #931)

- README.md
- _treehouses
- modules/help.sh
- modules/remote.sh
- package.json
> `treehouses remote allservices` (fixes #1044)

- _treehouses
- modules/remote.sh
- package.json
> `treehouses remote commands json` (fixes #1043)

- modules/globals.sh
- package.json
fixes #1054
added checkinternet function to `globals.sh` inside `modules`
> globals: `checkinternet` function (fixes #1054)

- modules/services.sh
- package.json
Fixes #1051
* Order functions alphabetically
* "Functionalize" `remove_tor_port`
> `treehouses services <service> down` also rm tor (fixes #1051)

- package.json
> update package.json with iot keyword (fixes #1065)

- modules/remote.sh
- package.json
> `treehouses remote` checkargn (fixes #1058)

- README.md
- _treehouses
- modules/help.sh
- modules/remote.sh
- package.json
> `treehouses remote check` (fixes #1083)

- modules/version.sh
- package.json
```bash
root@treehouses:~/cli# ./cli.sh version contributors
______________________________________________________________________
|:..                                                      ``:::%%%%%%HH|
|%%%:::::..                    I n t r o                     `:::::%%%%|
|HH%%%%%:::::....._______________________________________________::::::|
.    .        .      .             . .     .        .          .          .
.                 .                    .                .
.               A long time ago in a repo far, far away...   .
.               .           .               .        .             .
.      .            .                 .                                .
.      .         .         .   . :::::+::::...      .          .         .
.         .      . …
```
> `treehouses version contributors` alphabetical (fixes #1067)

- README.md
- modules/bluetooth.sh
- modules/help.sh
- package.json
Fixes #1070
```
bluetooth [on|off|pause|button|mac|id]
```
> `treehouses help bluetooth` (fixes #1070)

- modules/anime.sh
- modules/inspire.sh
- package.json
Fixes #1053
added `checkinternet` to `anime.sh` and `inspire.sh`
> `treehouses anime` & `inspire` checkinternet (fixes #1053)

- modules/remote.sh
- package.json
> `treehouses remote allservices` speedup (fixes #1082)

- package.json
- services/install-seafile.sh
Fixes #949
With tor inactive:
```
root@kjong:~/cli# treehouses tor status
inactive
root@kjong:~/cli# ./cli.sh services seafile install
Pulling seafile ... done
seafile installed
root@kjong:~/cli# docker-compose -f /srv/seafile/seafile.yml config
services:
seafile:
environment:
SEAFILE_ADDRESS: 192.168.1.154
SEAFILE_ADMIN: example@seafile.com
SEAFILE_ADMIN_PW: seacret
SEAFILE_NAME: Seafile
image: treehouses/rpi-seafile
ports:
- 8085:8000/tcp
- 8086:8086/tcp
volumes:
- /home/data/seafile:/seafile:rw
version: '3.0'
root@kjong:~/cli# ./cli.sh services seafile up
Creating network "seafile_default" with the default driver
Creating seafile_seafile_1 ... done
seafile built and started
root@kjong:~/cli# ./cli.sh services seafile url
192.168.1.154:8085
192.168.1.154:8086
```
Seafile accessible at …
> `treehouses services seafile` local/tor (fixes #949)

- services/install-ntopng.sh
> `treehouses services ntopng autorun` compose (fixes #1103)

- README.md
- _treehouses
- modules/detectwifi.sh
- modules/help.sh
- package.json
- tests/detectwifi.bats
fixes #1104
-checks for wifi module on device
> `treehouses detectwifi` (fixes #1104)

- _treehouses
- modules/led.sh
- package.json
- tests/led.bats
Fixes issue #1117 
- Adds `treehouses led stpatricks`
> `treehouses led stpatricks` (fixes #1117)

- README.md
- _treehouses
- modules/help.sh
- modules/upgrade.sh
- package.json
- tests/upgrade.bats
fixes #1116
-added `treehouses upgrade check`
-will eventually replace `--check` which still works
> `treehouses upgrade check` (fixes #1116)

- README.md
- _treehouses
- modules/help.sh
- modules/upgrade.sh
- package.json
- tests/upgrade.bats
fixes #1115
-added `treehouses upgrade force`
-will eventually replace `treehouses upgrade -f` which still works
> `treehouses upgrade force` (fixes #1115)

- README.md
- _treehouses
- modules/help.sh
- modules/services.sh
- package.json
> `treehouses services environment` without check (fixes #1113)

- _treehouses
- modules/led.sh
- package.json
- tests/led.bats
```bash
root@treehouses:~/cli# ./cli.sh led random
leds are set to dance mode.
Look at your RPi leds, green led will be in this pattern: 1 sec on; 1 off; 2 on; 1 off; 3 on; 1 off; 4 on; 1 off
green led: heartbeat
root@treehouses:~/cli# ./cli.sh led random lkjkl
leds are set to stpatricks mode.
Look at your RPi leds, both leds will be in this pattern...
Green LED: blink 2 times; on 1 sec; off 1 sec; this will happen 5 times
Green LED: flash 20 times; on 2 sec
red led: default-on
root@treehouses:~/cli#
```
> `treehouses led random` (fixes #989)

- package.json
- services/README.md
> update README.md in services (fixes #1159)

- _treehouses
- modules/power.sh
- package.json
Fixes #1173 
Add `treehouses power default`
> `treehouses power default` (fixes #1173)

- README.md
- _treehouses
- modules/discover.sh
- modules/help.sh
- package.json
- tests/discover.bats
> `treehouses discover wifi` (fixes #996)

- modules/discover.sh
- package.json
> `treehouses discover` refactor (fixes #1161)

- modules/upgrade.sh
- package.json
Added a new line to the upgrade_help function
> `treehouses help upgrade` spacing (fixes #1194)

- modules/power.sh
- package.json
> `treehouses help power` spacing (fixes #1204)

- modules/password.sh
- package.json
> `treehouses help password` spacing (fixes #1205)

- modules/services.sh
- package.json
> `treehouses services <service> start` (fixes #1224)

- _treehouses
- modules/services.sh
modified services.sh to include services <service_name>
> `treehouses services <service>` (fixes #965)

- modules/services.sh
- package.json
> treehouses services env check (fixes #1237)

- modules/remote.sh
- package.json
Fixes #1241
Takes a bit under 3 seconds on my machine.
Line breaks are included in the descriptions.
> treehouses remote help json (fixes #1241)

- README.md
- _treehouses
- modules/help.sh
- modules/led.sh
- package.json
- tests/led.bats
fixes #1260
- Add `treehouses led easter`
- Add missing `treehouses led <festivity>` to `README.md`
- Add missing `treehouses led <festivity>` to `modules/help.sh`
> `treehouses led easter` (fixes #1260)

- modules/globals.sh
- package.json
> `checkwrpi` detect bluetooth (fixes #1266)

- package.json
- services/install-kolibri.sh
```bash
root@treehouses:~/cli# ./cli.sh services kolibri install
Pulling kolibri ... done
kolibri installed
root@treehouses:~/cli# ./cli.sh services kolibri autorun
false
root@treehouses:~/cli# ./cli.sh services kolibri autorun true
service autorun set to true
root@treehouses:~/cli#
```
> `treehouses kolibri` more EOF (fixes #1296)

- _treehouses
- modules/help.sh
- modules/led.sh
- package.json
- tests/led.bats
Fixes issue #1175
Added a new holiday, Lantern to the modules of treehouses led.
Files modified:
```
./_treehouses
./modules/help.sh
./modules/led.sh
./package.json
./tests/led.bats
```
> `treehouses led lantern` (fixes #1175) 

- package.json
- services/README.md
Fixes #1306
* Change to heredoc instead of echo
> update `services/README.md` (fixes #1306)

- README.md
- _treehouses
- modules/help.sh
- modules/magazine.sh
- package.json
- tests/magazine.bats
fixes #1274
`treehouses magazine` module
> `treehouses magazine` (fixes #1274)

- modules/default.sh
- package.json
> `treehouses default network` wificountry (fixes #1325)

- README.md
- _treehouses
- modules/help.sh
- modules/led.sh
- package.json
- tests/led.bats
Added a new led mode 'kecak' (Balinese Hindu dance)
> `treehouses led kecak` (fixes #1333)

- README.md
- _treehouses
- modules/help.sh
- modules/magazine.sh
- package.json
- tests/magazine.bats
fixes #1348 
- hackspace magazine module
> `treehouses magazine hackspace` (fixes #1348)

- modules/magazine.sh
- package.json
- tests/magazine.bats
fixes #1347 
- different output for no args to magpi
> `treehouses magazine magpi` output (fixes #1347)

- package.json
- tests/magazine.bats
fixes #1328
- updated tests in the bats file
> `treehouses magazine magpi` tests (fixes #1328)

- modules/magazine.sh
- package.json
fixes #1317
- grabs latest issue number via web scraping
> `treehouses magazine magpi` & `hackspace` latest (fixes #1317)

- README.md
- _treehouses
- modules/help.sh
- modules/magazine.sh
- package.json
- tests/magazine.bats
fixes #1373
- added magazine module: wireframe
> `treehouses magazine wireframe` (fixes #1373)

- README.md
- modules/camera.sh
- modules/help.sh
- package.json
- captures h264 video and converts it to mp4
- length can be specified by a 2nd positional argument
- default length is 10 seconds
fixes #1225
> `treehouses camera record` (fixes #1225)

- modules/magazine.sh
- package.json
> `treehouses help magazine`

- package.json
- tests/services/grocy.bats
> `treehouses services grocy` test (fixes #1427)

- modules/upgrade.sh
- package.json
> `treehouses upgrade cli` sudo (fixes #1378) (fixes #1417)

- modules/magazine.sh
- package.json
> `treehouses magazine` moved checkinternet (fixes #1414)

- README.md
- _treehouses
- modules/help.sh
- modules/magazine.sh
- package.json
- tests/magazine.bats
fixes #1381 
- new magazine type added to module
> `treehouses magazine helloworld` (fixes #1381)

- README.md
- modules/help.sh
- modules/services.sh
- package.json
- services/install-transmission.sh
- tests/services/transmission.bats
fixes #1422 
```
root@treehouses:~/cli# ./cli.sh services transmission install
Pulling transmission ... done
transmission installed
root@treehouses:~/cli# ./cli.sh services transmission up
Creating network "transmission_default" with the default driver
Creating transmission_transmission_1 ... done
transmission built and started
tor active
adding port 9091
root@treehouses:~/cli# ./cli.sh services transmission ps
f9a49b2b2d7c        linuxserver/transmission          "/init"                  2 hours ago         Up 18 seconds              0.0.0.0:9091->9091/tcp, 0.0.0.0:51413->51413/tcp, 0.0.0.0:51413->51413/udp   transmission_transmission_1
```
running successfully and downloaded something
> `treehouses services transmission` (fixes #1422)

- modules/wifi.sh
- package.json
> `treehouses wifi` enterprise addition (fixes #1452)

- modules/wifi.sh
- package.json
> `treehouses wifi` enterprise addition (fixes #1464)

- package.json
- services/install-invoiceninja.sh
- tests/services/invoiceninja.bats
- tests/test.sh
fixes https://github.com/treehouses/cli/issues/1434
still have error in
1. services invoiceninja up
2. services invoiceninja restart
> `treehouses services invoiceninja` test port 8090 (fixes #1434)

- package.json
- tests/test.sh
> update `test.sh` (fixes #1468)

- modules/sshtunnel.sh
- package.json
> `treehouses help sshtunnel` improve (fixes #1473)

- _treehouses
- package.json
> `treehouses magazine` completion (fixes #1500)

- _treehouses
- package.json
> `treehouses remote commands [json]` (fixes #1499)

- magazine/download-hackspace.sh
- magazine/download-helloworld.sh
- magazine/download-magpi.sh
- magazine/download-wireframe.sh
- modules/magazine.sh
- package.json
Fixes #1503
Fixes #1505
Fixes #1509
Might break some magazine functionality / tests
> `treehouses magazine` un-`set -e` (fixes #1503) (fixes #1509)

- _treehouses
- modules/sshtunnel.sh
- package.json
> `treehouses sshtunnel key verify` (fixes #1490)

- modules/led.sh
- package.json
> `treehouses led lantern` description (fixes #1515)

- modules/led.sh
- package.json
> `treehouses led lunarnewyear` pattern (fixes #1513)

- README.md
- modules/help.sh
- package.json
> update `README.md` (fixes #1514)

- README.md
- _treehouses
- modules/help.sh
- modules/led.sh
- tests/led.bats
add a new led mode `dragonboat`
> `treehouses led dragonboat` (fixes #1535)

- modules/led.sh
- package.json
> `treehouses led thanksgiving` refactor (fixes #1519)

- README.md
- _treehouses
- modules/help.sh
- modules/sshtunnel.sh
- package.json
> `treehouses sshtunnel ports` (fixes #1547)

- modules/help.sh
> Updated 'treehouses power' in help.sh (fixes #1561)

- README.md
> updated 'treehouses default' in README.md (fixes #1566)

- modules/sshtunnel.sh
> `treehouses sshtunnel` send notice on ports change (fixes #1545)

- README.md
> Add few improving changes in README.md

- README.md
- modules/help.sh
- package.json
> `treehouses help` (fixes #1571)

- README.md
- modules/help.sh
- package.json
> `treehouses help default` (fixes #1559)

- modules/remote.sh
- package.json
> `treehouses remote` refactor (fixes #1564)

- README.md
- _treehouses
- modules/help.sh
- modules/led.sh
- package.json
- tests/led.bats
Fixes #1588
Added new led pattern.
> `treehouses led independenceday` (fixes #1588)

- modules/led.sh
- package.json
> `treehouses led easter` rework (fixes #1538)

- modules/led.sh
- package.json
> `treehouses led lantern` rework (fixes #1539)

- modules/led.sh
- package.json
> `treehouses led onam` rework (fixes #1537)

- modules/ssh.sh
- package.json
> `treehouses ssh` refactor (fixes #1578)

- modules/bluetooth.sh
- package.json
> `treehouses bluetooth` refactor (fixes #1582)

- modules/gpio.sh
- package.json
> `treehouses gpio` zero W (fixes #1609)

- README.md
- _treehouses
- modules/discover.sh
- modules/help.sh
- package.json
- tests/discover.bats
fixes #510
sample output:
```
root@treehouses:~# treehouses discover gateway 
ip address: 192.168.1.1
PORT      STATE SERVICE
80/tcp    open  http
5080/tcp  open  onscreen
5678/tcp  open  rrac
8080/tcp  open  http-proxy
52869/tcp open  unknown
MAC Address: C0:13:2B:5C:A2:26 (Unknown)
```
```
root@treehouses:~# treehouses discover gateway list
192.168.1.3      ea:da:b3:1a:1d:1d
192.168.1.5      c2:ff:63:a2:ad:45
192.168.1.6      f4:5c:89:ae:d8:69
```
> `treehouses discover gateway` (fixes #510)

- README.md
- _treehouses
- magazines/download-hackspace.sh
- magazines/download-helloworld.sh
- magazines/download-magpi.sh
- magazines/download-wireframe.sh
- modules/help.sh
- modules/magazines.sh
- package.json
> `treehouses magazines downloaded` (fixes #1595)

- modules/picture.sh
- package.json
> `treehouses picture` check (fixes #1628)

- package.json
- services/install-librespeed.sh
> `treehouses services librespeed` less env (fixes #1649)

- package.json
- services/install-grocy.sh
> `treehouses services grocy` less env (fixes #1648)

- modules/picture.sh
- package.json
> `treehouses picture` check for `tiv` binary (fixes #1643)

- _treehouses
- package.json
> `treehouses memory` completion (fixes #1669)

- README.md
- _treehouses
- modules/help.sh
- modules/uptime.sh
- package.json
> `treehouses uptime log` (fixes #1645)

- magazines/README.md
- modules/magazines.sh
- package.json
> `treehouses magazines` `README.md` added (fixes #1642)

- README.md
- _treehouses
- modules/discover.sh
- modules/help.sh
- package.json
- tests/discover.bats
fixes #1652 
---
sample output:
```
root@treehouses:~# treehouses discover self
IP address:
192.168.0.102
MAC address:
eth0:	b8:27:eb:1f:5b:e7
wlan0:	b8:27:eb:4a:0e:b2
Ports:
ss-local           1081
ss-local           1080
sshd             22
exim4             25
docker-pr           2200
docker-pr             80
tor           9050
systemd-r           5355
sshd           6010
dnsmasq             53
```
> `treehouses discover self` (fixes #1652)

- README.md
- _treehouses
- magazines/download-hackspace.sh
- magazines/download-helloworld.sh
- magazines/download-magpi.sh
- magazines/download-wireframe.sh
- modules/help.sh
- modules/magazines.sh
- package.json
- tests/magazines/hackspace.bats
- tests/magazines/helloworld.bats
- tests/magazines/magpi.bats
- tests/magazines/wireframe.bats
> `treehouses magazines <magtype> url` (fixes #1641)

- modules/services.sh
- package.json
> `treehouses services` help when error (fixes #1673)

- modules/services.sh
- package.json
> `treehouses services` check for `docker-compose` (fixes #1662)

- modules/remote.sh
- package.json
> `treehouses remote allservices` with `size` (fixes #1681)

- README.md
- _treehouses
- modules/help.sh
- modules/message.sh
- package.json
> `treehouses message gitter receivefrom` (fixes #1686)

- modules/globals.sh
- modules/picture.sh
- modules/usb.sh
- package.json
> global: `check_missing_binary` added (fixes #1657)

- modules/sshtunnel.sh
- package.json
> `treehouses sshtunnel` no output if notice enabled (fixes #1717)

- modules/remote.sh
- package.json
fixes https://github.com/treehouses/cli/issues/1668
> `treehouses remote statuspage` (fixes #1668)

- _treehouses
- package.json
> `treehouses discover` completion (fixes #1733)

- package.json
- services/install-webssh.sh
> `treehouses services webssh` multi-arch

- README.md
- _treehouses
- modules/help.sh
- modules/internet.sh
- package.json
> `treehouses internet reverse` (fixes #1722)

- modules/globals.sh
- modules/services.sh
- package.json
> global: `check_missing_binary` refactor (fixes #1701)

- modules/magazines.sh
- package.json
fixes #1637
- sorts downloaded magazines accordingly
> `treehouses magazines` refactor (fixes #1637)

- magazines/README.md
- package.json
> `treehouses magazines` README.md (fixes #1692)

- modules/shadowsocks.sh
- package.json
> `treehouses shadowsocks` refactor

- README.md
- _treehouses
- modules/help.sh
- modules/remote.sh
- package.json
- tests/remote.bats
> `treehouses remote statuspage` with storage (fixes #1723)

- modules/internet.sh
- package.json
- tests/internet.bats
> `treehouses internet reverse` test (fixes #1749)

- package.json
- tests/memory.bats
> `treehouses memory` test (fixes #1741)

- _treehouses
- package.json
fixes #1739 
alternate fix to #1743
> `treehouses` bash completion dynamic path (fixes #1739)

- modules/internet.sh
- package.json
> `treehouses internet reverse` refactor (fixes #1737)

- modules/internet.sh
- package.json
> `treehouses internet reverse` check internet (fixes #1736)

- README.md
- _treehouses
- modules/help.sh
- modules/storage.sh
- package.json
- tests/storage.bats
> `treehouses storage` (fixes #1672)

- modules/ssh.sh
- package.json
> `treehouses ssh 2fa` enhancements (fixes #1766)

- README.md
- _treehouses
- modules/help.sh
- modules/version.sh
- package.json
- tests/version.bats
> `treehouses version remote` (fixes #1764)

- modules/storage.sh
- package.json
> `treehouses storage` output overview (fixes #1760)

- modules/ssh.sh
- package.json
fixes https://github.com/treehouses/cli/issues/1801
> `treehouses ssh 2fa remove <user>` output (fixes #1801)

- modules/bluetooth.sh
- package.json
> `treehouses bluetooth pause` (fixes #1774)

- README.md
- _treehouses
- modules/help.sh
- modules/ssh.sh
- package.json
> `treehouses help ssh` 2fa  (fixes #1829)

- modules/globals.sh
- package.json
> new `check_missing_binary <binary> [instructions]` (fixes #1807)

- modules/usb.sh
- package.json
> `treehouses usb` install instructions (fixes #1820)

- modules/picture.sh
- package.json
> `treehouses picture` install instructions (fixes #1819)

- modules/services.sh
- package.json
> `treehouses services` install instructions (fixes 1821)

- modules/services.sh
- package.json
fixes https://github.com/treehouses/cli/issues/1814
> `treehouses services <service> url tor` output (fixes #1814)

- modules/remote.sh
- package.json
> `treehouses remote statuspage` with wificountry (fixes #1815)

- modules/services.sh
- package.json
fixes https://github.com/treehouses/cli/issues/1813
> `treehouses services cleanup` suppressed warnings (fixes #1813)

- modules/remote.sh
- package.json
> `treehouses remote statuspage` wificountry slim (fixes #1839)

- README.md
- _treehouses
- modules/help.sh
- modules/remote.sh
- package.json
> `treehouses remote ssh2fa` (fixes #1817)

- modules/apchannel.sh
- package.json
> `treehouses apchannel` refactor error output (fixes #1882)

- modules/remote.sh
- package.json
> `treehouses remote` refactor error output (fixes #1885)

- modules/memory.sh
- package.json
> `treehouses memory` refactor error output (fixes #1864)

- modules/storage.sh
- package.json
> `treehouses storage` refactor error output (fixes #1868)

- modules/ssh.sh
- package.json
> `treehouses ssh` refactor error output (fixes #1874)

- modules/config.sh
- package.json
> `treehouses config` refactor error output (fixes #1862)

- modules/sshkey.sh
- package.json
> `treehouses sshkey` refactor error output (fixes #1880)

- modules/tor.sh
- package.json
> `treehouses tor` refactor error output (fixes #1872)

- modules/discover.sh
- package.json
> `treehouses discover` refactor error output (fixes #1887)

- modules/bluetooth.sh
- package.json
> `treehouses bluetooth` refactor error output (fixes #1889)

- modules/internet.sh
- package.json
> `treehouses internet` refactor error output (fixes #1891)

- modules/log.sh
- package.json
> `treehouses log` log_comment_and_exit1 function (fixes #1896)

- README.md
- modules/help.sh
- modules/services.sh
- package.json
- services/install-sysmon.sh
- tests/services/sysmon.bats
> `treehouses services sysmon` (fixes #1847)

- modules/globals.sh
- package.json
> `treehouses globals` refactor error outputs (fixes #1904)

- modules/discover.sh
- package.json
> `treehouses discover` no error (fixes #1893)

- modules/shadowsocks.sh
- package.json
> `treehouses shadowsocks` refactor error output (fixes #1860)

- modules/sshtunnel.sh
- package.json
> `treehouses sshtunnel` refactor error output (fixes #1869)

- modules/services.sh
- package.json
> `treehouses services` refactor error output (fixes #1866)

- modules/log.sh
- package.json
> `treehouses log` log_help_and_exit1 function (fixes #1903)

- modules/shadowsocks.sh
- package.json
> `treehouses shadowsocks` refactor error output (fixes #1938)

- modules/redirect.sh
- package.json
> `treehouses redirect` refactor output (fixes #1940)

- modules/power.sh
- package.json
> `treehouses power` refactor output (fixes #1934)

- modules/discover.sh
- package.json
> `treehouses discover` refactor output (fixes #1932)

- modules/uptime.sh
- package.json
> `treehouses uptime` refactor output (fixes #1942)

- modules/services.sh
- package.json
> `treehouses services` refactor output (fixes #1936)

- modules/internet.sh
- package.json
> `treehouses internet` refactor output (fixes #1944)

- modules/rtc.sh
- package.json
> `treehouses rtc` refactor output (fixes #1954)

- modules/ntp.sh
- package.json
> `treehouses ntp` refactor output (fixes #1976)

- modules/timezone.sh
- package.json
> `treehouses timezone` refactor output (fixes #1950)

- modules/magazines.sh
- package.json
> `treehouses magazine` refactor output (fixes #1970)

- modules/detect.sh
- package.json
> `treehouses detect` refactor output (fixes #1978)

- modules/version.sh
- package.json
> `treehouses version` refactor output (fixes #1980)

- modules/camera.sh
- package.json
> `treehouses camera` refactor output (fixes #1972)

- modules/verbose.sh
- package.json
> `treehouses verbose` refactor output (fixes #1982)

- modules/coralenv.sh
- package.json
> `treehouses coralenv` refactor output (fixes #1974)

- modules/usb.sh
- package.json
> `treehouses usb` refactor output 2nd (fixes #1946)

- modules/locale.sh
- package.json
> `treehouses locale` refactor output (fixes #1952)

- modules/bootoption.sh
- package.json
> `treehouses bootoption` refactor output (fixes #1962)

- modules/changelog.sh
- package.json
> `treehouses changelog` refactor output (fixes #1948)

- modules/openvpn.sh
- package.json
> `treehouses openvpn` refactor output (fixes #1961)

- modules/vnc.sh
- package.json
> `treehouses vnc` refactor error output (fixes #1966)

- modules/staticwifi.sh
- package.json
> `treehouses staticwifi` refactor output (fixes #1968)

- modules/bridge.sh
- package.json
> `treehouses bridge` refactor output (fixes #1956)

- modules/ap.sh
- package.json
> `treehouses ap` refactor output (fixes #1960)

- modules/wifi.sh
- package.json
> `treehouses wifi` refactor output (fixes #1958)

- modules/message.sh
- package.json
fixes https://github.com/treehouses/cli/issues/1994
> `treehouses message gitter` new app key (fixes #1994)

- modules/services.sh
- package.json
- services/README.md
- services/install-couchdb.sh
- services/install-pihole.sh
- services/install-sysmon.sh
fixes https://github.com/treehouses/cli/issues/1992
> `treehouses services <service> url` with full path (fixes #1992)

- README.md
- _treehouses
- modules/help.sh
- modules/message.sh
- package.json
fixes https://github.com/treehouses/cli/issues/1810
> `treehouses message slack send`(fixes #1810)

- modules/message.sh
- package.json
fixes https://github.com/treehouses/cli/issues/2006
> `treehouses message slack apitoken` check (fixes #2006)

- README.md
- modules/help.sh
- modules/message.sh
fixes https://github.com/treehouses/cli/issues/2021
> `treehouses message gitter channels` (fixes #2021)

- README.md
- _treehouses
- modules/help.sh
- modules/led.sh
- package.json
- tests/led/sandstorm.bats
Add `sandstorm`  sub-sub command `treehouses led`.
> `treehouses led sandstorm` (fixes #2036)

- modules/led.sh
- package.json
Fix inconsistent indentation in `led.sh`.
> `treehouses led` refactor (fixes #2041)

- README.md
- _treehouses
- modules/help.sh
- modules/remote.sh
- package.json
> `treehouses remote reverse` (fixes #2068)

- package.json
- services/install-sysmon.sh
fixes https://github.com/treehouses/cli/issues/2069
> `treehouses remote help` last arches (fixes #2069)

- README.md
- _treehouses
- modules/help.sh
- modules/password.sh
- package.json
- tests/password.bats
I'm still debugging using a case inside a case.
> `treehouses password change` (fixes #2072)

- modules/feedback.sh
- package.json
- tests/feedback.bats
> `treehouses feedback` error code (fixes #2175)

- modules/detect.sh
- package.json
> `treehouses detect` for revisions 1.4 of 4B (fixes #2250)

- modules/detect.sh
- package.json
> `treehouses detect` for Pi 400 (fixes #2251)

- modules/detect.sh
- package.json
> `treehouses detect` for CM4 (fixes #2252)

- modules/detect.sh
- package.json
> `treehouses detect` for Zero 2 W (fixes #2253)

- README.md
- modules/help.sh
- package.json
- services/install-epaath.sh
https://hub.docker.com/r/olenepal/epaath
https://epaath.olenepal.org
> `treehouses services epaath` for arm

- modules/feedback.sh
- package.json
> `treehouses feedback` better output (fixes #2287)

- modules/detect.sh
- package.json
> `treehouses detect` add rpi5 and more (fixes #2289)

- modules/led.sh
- package.json
> `treehouses led` also for cube image (fixes #2291)

- modules/led.sh
- package.json
> `treehouses led` better help message (fixes# 2293)

- .github/workflows/newversion.yml
- package.json
> actions: bump node to 20 (fixes #2300)
